# Generated by Django 4.2 on 2023-04-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Event_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
