# Generated by Django 4.2 on 2023-04-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_event_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='CourseDescription',
            field=models.TextField(null=True),
        ),
    ]
